### ISSUE TITLE
raiplay-dl is not an internal or external command, nor is it a runnable program or batch file

### ISSUE THREAD

**Issue by a4d5g6** [leoncvlt/raiplay-dl#5]
Hello, I have successfully installed files as requirements.txt requires. However, the cmd says that raiplay-dl is not an internal or external command, nor is it a runnable program or batch file. Could you please tell me how to solve this problem? Or should I add something to the PATH? Thanks a lot!

**Comment by leoncvlt** [comment]
That sounds like you're running `raiplay-dl` directly, you should run it with python: `python raiplay-dl.py`

**Comment by a4d5g6** [comment]
Hi, Leo! Could you please have a check at the example below? I have no idea how to run the code, thanks for your patience!

`C:\Users\Administrator>cd/d D:\raiplay-dl-master

D:\raiplay-dl-master>raiplay-dl.py -h -d F:\raiplay https://www.raiplay.it/video/2017/11/La-figlia-del-Capitano---E1-787356ed-71cd-41b6-90b2-6c4a0bc138bf.html
  **File "D:\raiplay-dl-master\raiplay-dl.py", line 25
    print(f"Download directory set to {download_dir}")**
                                                    ^
**SyntaxError: invalid syntax**`
![code](https://user-images.githubusercontent.com/59647280/83024533-1dc5de00-a061-11ea-8e9e-a360560a3c99.png)
![Uploading code.png…]()

**Comment by leoncvlt** [comment]
The command should be `python raiplay-dl.py -d F:\raiplay https://www.raiplay.it/video/2017/11/La-figlia-del-Capitano---E1-787356ed-71cd-41b6-90b2-6c4a0bc138bf.html` - the `-h` flag shouldn't be there.

Do you have python installed? If not, you need to install it first: https://realpython.com/installing-python/#windows

**Comment by a4d5g6** [comment]
It did worked this time, but it seemed that foreigners who live out of Italy cannot download videos due to geo restriction. My lantern VPN  doesn't provide me agent service for Italy, that's too bad! So I could only reckon on visiting Italy oneday for this purpose. By the way, thank you so much for delicated work and guidance, hope you develop more powerful downloading tool and have a successful future in the days to come. 
Best wishes!
![code](https://user-images.githubusercontent.com/59647280/83038484-97fd5f00-a06f-11ea-8ea9-ebe89913cba7.png)
![La figlia del Capitano - E1 mp4_20200527_225928 966](https://user-images.githubusercontent.com/59647280/83038490-99c72280-a06f-11ea-8f69-40a4a12c5536.jpg)

**Comment by leoncvlt** [comment]
Interesting! Haven't seen that one before. I'll flag this up in a separate issue and close this. Thanks for bringing this up!
